### ISSUE TITLE
Course / Lesson "Multi Line" Textarea

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#102]
https://mcaprotools.com/course/6-figures-formula/

In this course, after each video the student must fill out a "Quiz":

![screen shot 2017-05-04 at 4 44 46 am](https://cloud.githubusercontent.com/assets/10511034/25696281/8fa54e16-3084-11e7-916e-911e7fd7726d.png)

In this case, the "Quiz" is a "Multi Line" question.  Which appears on the frontend of the lesson like this currently:

![screen shot 2017-05-04 at 4 32 05 am](https://cloud.githubusercontent.com/assets/10511034/25696386/033014ec-3085-11e7-9754-5da3179bd571.png)

However, the client does not like that the user has to click on the "View The Quiz" button. (it forwards to another page - Example: https://mcaprotools.com/quiz/the-results-creating-a-fan-page/). Instead, we need it to appear like so: 

![textarea-multiline](https://cloud.githubusercontent.com/assets/10511034/25696434/2df6a3c6-3085-11e7-9dfe-9a7b76aa391f.jpg)

Here is the 1 RULE, the "Mark This Lesson Complete" Button does not appear until the user "Saves" the response for the lesson.

![appear-after](https://cloud.githubusercontent.com/assets/10511034/25696497/5fad4e88-3085-11e7-8071-c3d88ca324bf.jpg)

**Comment by sgerritse** [comment]
There is extra text, sections on the "completed lessons".

![screen shot 2017-05-12 at 4 25 20 pm](https://cloud.githubusercontent.com/assets/10511034/26015628/c6882a82-372f-11e7-9a28-9e6137bd4c8a.jpg)

- There is also no way to "edit / reset" my summary.
- Add 1px border around the textarea

**Comment by tarundhanwani** [comment]
The tasks in the last comment are done -

1. Extra text sections removed.

2. To edit the summary, simply write a text in the text area, click save, and if you want to edit it or reset/remove it, simply change (or remove) the text in the text area and click save again.

3. 1px border added around text area.
