### ISSUE TITLE
List "in course lesson"

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#105]
Go to this lesson: https://mcaprotools.com/lesson/edit-videos-in-mca-pro-tools/

You will see we have a "List", but the bullets don't show?  Please make it look like this:
![screen shot 2017-05-04 at 3 36 28 pm](https://cloud.githubusercontent.com/assets/10511034/25721756/9fbabfec-30df-11e7-850d-3598eb38a81e.png)

**Comment by webskycreative** [comment]
@sgerritse 

fixed 
https://mcaprotools.com/lesson/edit-videos-in-mca-pro-tools/
https://www.screencast.com/t/WkuBNzasiF

thanks
