### ISSUE TITLE
Dashboard "Button"

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#109]
If you look at the first few seconds of the video on the /dashboard/ you will notice that we have a "red button" that says "Start Your First Lesson".

Currently, we have this on the /dashboard/:
![screen shot 2017-05-05 at 3 56 53 am](https://cloud.githubusercontent.com/assets/10511034/25737676/1e905e5a-3147-11e7-8b0e-ac473cefd3f9.png)

We need to have the red button there that links directly to the "FIRST" course, of whatever package the member purchased.

So for example:
- MCA Pro Tools Membership (Product / 3 Courses)
(Button would link too: https://mcaprotools.com/course/initial-setup/)

- 6 Figure Formula (Product / 1 Course)
(Button would link too: https://mcaprotools.com/course/6-figures-formula/)

We may add more courses / packages like this in future so please keep that in mind when coding.

**Comment by sgerritse** [comment]
If the customer has both packages, it links to the initial setup first.

**Comment by sgerritse** [comment]
@webskycreative I would also like you to do the same function on this page "Order Received".

![screen shot 2017-05-12 at 4 38 40 pm](https://cloud.githubusercontent.com/assets/10511034/26016089/96da5b46-3731-11e7-9111-5aeee864b6cc.png)

**Comment by webskycreative** [comment]
@sgerritse 

fixed https://www.screencast.com/t/xYbvD4sYQ

thanks
