### ISSUE TITLE
Popup "Pushed Down / Far Away"

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#110]
On these pages the "popup" displays weird. It makes the user scroll down before they can see the "popup". (Make sure it functions properly on mobile too).

- https://www.mcaprotools.com/testimonials/?ref=
![testimonials_popup](https://cloud.githubusercontent.com/assets/10511034/25972734/35e0eaca-366f-11e7-9dc0-2895600af920.png)

- https://www.mcaprotools.com/benefits/?ref=
![benefits_popup](https://cloud.githubusercontent.com/assets/10511034/25972740/38b7ba76-366f-11e7-87d7-2cf8fa67332b.png)

- https://www.mcaprotools.com/notsleepingvideo/?ref=
![popup-gap](https://cloud.githubusercontent.com/assets/10511034/25972745/3bbfe4e6-366f-11e7-85cb-c0d73eae0776.png)

**Comment by webskycreative** [comment]
@sgerritse 

fixed
https://mcaprotools.com/testimonials/?ref=demouser
https://www.mcaprotools.com/benefits/?ref=demouser
https://www.mcaprotools.com/notsleepingvideo/?ref=demouser

thx
