### ISSUE TITLE
"Sign Up Button"

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#112]
Style "Cart Sign Up Button":

![signup-button](https://cloud.githubusercontent.com/assets/10511034/25972940/02318710-3670-11e7-83da-4c62ead05eb5.png)

To look like this (should be similar on mobile):
![signup-button](https://cloud.githubusercontent.com/assets/10511034/25973046/77d3f340-3670-11e7-9efd-492b86f6173d.png)

** Also fix the "Card Icons" placement: **
![screen shot 2017-05-11 at 5 37 45 pm](https://cloud.githubusercontent.com/assets/10511034/25973072/90d59998-3670-11e7-94d1-0a6d0af307da.png)

**Comment by webskycreative** [comment]
@sgerritse 

fixed
https://mcaprotools.com/checkout/
https://www.screencast.com/t/fqcnfyEecE

thx
