### ISSUE TITLE
Your Invited Page Styling

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#113]
On Mobile It looks like this:

![img_0820](https://cloud.githubusercontent.com/assets/10511034/25973137/d6cee62a-3670-11e7-8744-38e537d11f7d.PNG)

![img_0821](https://cloud.githubusercontent.com/assets/10511034/25973146/dc60a0ba-3670-11e7-9839-4b90cabbeabb.PNG)

**Comment by webskycreative** [comment]
@sgerritse 

fixed https://www.screencast.com/t/ygB15iBiB

thx
