### ISSUE TITLE
Background Image Styling

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#129]
The client mentions that the following pages have this issue (white spacing / especially on mobile)

![screen shot 2017-05-25 at 2 38 02 pm](https://cloud.githubusercontent.com/assets/10511034/26465045/ccea02e2-4157-11e7-959d-f994fb332c7f.png)

![screen shot 2017-05-25 at 2 39 14 pm](https://cloud.githubusercontent.com/assets/10511034/26465088/f418f97c-4157-11e7-9529-70cca84bee47.png)

- https://mcaprotools.com/bizvideo/
- I would suggest checking all the pages here: https://mcaprotools.com/marketing-hub/links/ 

(so we don't get further complaints from client regarding these issues on other pages)

**Comment by tarundhanwani** [comment]
Hi, I'm about halfway through the amount of landing pages with the background image on those marketing links pages. Each page has its own css styling and bg image, so I'm modifying each one to get from the global css styles that I added specific for background pages that have the fix in place. These are the ones that are done so far -

https://mcaprotools.com/bizvideo/
https://mcaprotools.com/discover/?ref=ptadmin
https://mcaprotools.com/pushstart/?ref=ptadmin
https://mcaprotools.com/laptoplife/?ref=ptadmin
https://mcaprotools.com/pushct4/?ref=ptadmin
https://mcaprotools.com/500s/?ref=ptadmin

I'll finish up the other remaining landing pages from the marketing links later today.

Note - When testing on mobile, it's important that you clear cache, I did do a server side clearing of cache, but still just to be on the safe side.

Also, I've been checking each page meticulously using http://browserstack.com/ which lets me preview pages on actual mobile devices.

**Comment by sgerritse** [comment]
I think these are still having an issue:
- https://mcaprotools.com/pushstart/?ref=ptadmin
![screen shot 2017-05-28 at 1 30 50 am](https://cloud.githubusercontent.com/assets/10511034/26526335/4c4c4a42-4345-11e7-80b0-595e935c2fbf.png)

- https://mcaprotools.com/pushct4/?ref=ptadmin
![screen shot 2017-05-28 at 1 31 19 am](https://cloud.githubusercontent.com/assets/10511034/26526338/5df9b040-4345-11e7-973b-31bfc72b9ee4.png)

- https://mcaprotools.com/500s/?ref=ptadmin
![screen shot 2017-05-28 at 1 31 46 am](https://cloud.githubusercontent.com/assets/10511034/26526341/6f07d326-4345-11e7-8953-efb32d13a6d5.png)

...Yes,  cleared my cache & all...
