### ISSUE TITLE
Checkout has "Extra Buttons"?

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#133]
Try to checkout with MCA Pro Tools Membership: https://mcaprotools.com/checkout/

![screen shot 2017-05-26 at 5 35 25 am](https://cloud.githubusercontent.com/assets/10511034/26489398/374f0e66-41d5-11e7-889b-af31e5ee96da.png)

You can see there are two, "Continue" buttons  which serve no purpose.

**Comment by sgerritse** [comment]
Also noticed that there is an entire extra section showing. (it seems to be a duplicate of the "cart total" div / function calls.)

![screen shot 2017-05-26 at 10 33 08 pm](https://cloud.githubusercontent.com/assets/10511034/26517275/609e712e-4263-11e7-8d77-a07a56ba23d7.png)


Whereas, this is the only thing that should show would be one "cart total":

![screen shot 2017-05-26 at 10 34 19 pm](https://cloud.githubusercontent.com/assets/10511034/26517295/81ed111e-4263-11e7-92d0-61899ef8fe8f.png)

**Comment by tarundhanwani** [comment]
This should be solved. Tested and verified that all functionalities work after removing the continue buttons, the additional information section and the extra total div section in the cart page.

Thanks
