### ISSUE TITLE
"Inner Lesson" showing "Course Menu"

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#136]
![screen shot 2017-05-31 at 8 35 31 pm](https://cloud.githubusercontent.com/assets/10511034/26659848/00edefba-4642-11e7-90a9-e405d62e1328.png)

A. When viewing any of the lessons, (https://mcaprotools.com/lesson/connect-your-mca-username/) it seems that the "Left Menu" is showing the "Course Menu" instead of the "Lesson" menu.

B. If you look at the Video, you will see that at one point it was displaying the "Lessons Menu" on the left. (Example)

**Comment by tarundhanwani** [comment]
Hi, the proper Lessons Menu items are now visible on the single lesson inner page template.

Thanks
