### ISSUE TITLE
Add Icons to /mcaprotools-invite/

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#20]
The Icons need to be added to this page: http://mcaprotools.com/mcaprotools-invite/
![protools-icons](https://cloud.githubusercontent.com/assets/10511034/22966931/48a53dee-f332-11e6-96de-ab446b1c50ef.jpg)

Download icons here:
https://drive.google.com/open?id=0B9QlVpKDdRNvOFZUOURWdi1USjg

**Comment by sgerritse** [comment]
Please also update the buy buttons on this page to look like this on desktop & mobile.

![protools-buy-mobile](https://cloud.githubusercontent.com/assets/10511034/22967387/3d4f6a44-f334-11e6-8ea7-3b91172f2d81.jpg)

![protools-buy-desktop](https://cloud.githubusercontent.com/assets/10511034/22967386/3d4f65c6-f334-11e6-891d-42eb1522d049.jpg)

---

Here is the icon .svg to use for the button.
http://www.flaticon.com/free-icon/fast-forward-double-right-arrows_60678#term=double arrow

**Comment by sgerritse** [comment]
Edit this section:
![img_1181](https://cloud.githubusercontent.com/assets/10511034/23228772/cb3eb3aa-f90b-11e6-8b72-ac43d5a553c1.PNG)

To make it look like this:
![price](https://cloud.githubusercontent.com/assets/10511034/23228801/e0f1d5d8-f90b-11e6-9cc9-b449fac8cf0f.jpg)

**Comment by tarundhanwani** [comment]
These changes have been addressed.

Thanks

**Comment by tarundhanwani** [comment]
The buttons and some of the stylings were not applied because of the change of class names. Re applying the changes.

**Comment by tarundhanwani** [comment]
Changes to the buttons plus some of the content that are specified in the comments above are all in place.
