### ISSUE TITLE
http://mcaprotools.com/cart/

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#21]
ERORR: The "Cart Totals" is showing twice?
![screen shot 2017-02-15 at 4 12 48 am](https://cloud.githubusercontent.com/assets/10511034/22967589/164d70e8-f335-11e6-91a3-6baeff74b1b8.png)

Update styling show it looks / function as:
![checkout](https://cloud.githubusercontent.com/assets/10511034/22968029/dae02544-f336-11e6-9951-9a06b71289b2.png)

Icons here:
- http://www.flaticon.com/free-icon/thin-right-arrow_7556#term=thin arrow&page=1&position=13
- http://www.flaticon.com/free-icon/reload_130466#term=thin arrow&page=1&position=14

**Comment by juandlr** [comment]
its not an error, the plugin is doing this, it shows both recurring and other item cart totals, we can hide some of them if you want

**Comment by sgerritse** [comment]
If you can make it look like the jpg that would be ideal.

**Comment by tarundhanwani** [comment]
The duplicate cart section has been removed and the remaining one has been redesigned to look like the jpg attached.

Thanks
