### ISSUE TITLE
On "Order Received" 

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#23]
After you make successful payment MEMBERSHIP, it forwards you to "Order Received"
http://mcaprotools.com/checkout/order-received/2927/?key=wc_order_58a425764a13d

We need to add a "Button" above the "View Order" area (THIS WOULD ONLY SHOWS FOR MEMBERSHIP ORDERS)
![view-order-membership](https://cloud.githubusercontent.com/assets/10511034/22969294/f580942e-f33b-11e6-9c08-fd411daa98e5.jpg)

**Comment by tarundhanwani** [comment]
The red button bar has been added to the thank you page template/order received page.

Thanks
