### ISSUE TITLE
Fix Responsiveness / Styling

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#24]
The following pages must be 100% responsive & remove any visual sores / bugs.

MCA Capture Pages: 
1. http://www.mcaprotools.com/notsleepingvideo/
2. http://www.mcaprotools.com/losingsleep/
3. http://www.mcaprotools.com/2kperweek/

MCA Landing Pages
1. http://www.mcaprotools.com/whatismca/ 
2. http://www.mcaprotools.com/benefits/
3. http://www.mcaprotools.com/testimonials/

Pro Tools Pages
1. http://mcaprotools.com/mcaprotools-invite/
2. http://www.mcaprotools.com/hangout/

Account Pages:
1. http://mcaprotools.com/my-account/
2. http://mcaprotools.com/my-account/orders/
3. http://mcaprotools.com/my-account/subscriptions/
4. http://mcaprotools.com/my-account/edit-address/
5. http://mcaprotools.com/my-account/edit-account/

Lessons / Courses:
1. http://mcaprotools.com/training-hub/
(Go through each lesson - Make sure all videos etc are responsive)

Offline Marketing:
1. Business Cards: http://mcaprotools.com/product/mca-2-x-3-5-business-cards/ 
2. Flyers: http://mcaprotools.com/product/mca-8-5-x-11-flyers/ 
3. Postcards: http://mcaprotools.com/product/4x6-mca-handouts/

**Comment by sgerritse** [comment]
Please also update the buy buttons on this page to look like this on desktop & mobile.

![protools-buy-mobile](https://cloud.githubusercontent.com/assets/10511034/22967387/3d4f6a44-f334-11e6-8ea7-3b91172f2d81.jpg)

![protools-buy-desktop](https://cloud.githubusercontent.com/assets/10511034/22967466/91252d5c-f334-11e6-8970-7063794ebf6e.jpg)

---

Here is the icon to use for the button.
http://www.flaticon.com/free-icon/fast-forward-double-right-arrows_60678#term=double arrow

**Comment by sgerritse** [comment]
On http://www.mcaprotools.com/whatismca/:

Make the top portion look like this:
![mobile_whatismca](https://cloud.githubusercontent.com/assets/10511034/23156484/18ee8de6-f7e5-11e6-8b23-d6a8f6d79156.jpg)

Also make the buy buttons on mobile look like this:

![protools-buy-mobile](https://cloud.githubusercontent.com/assets/10511034/22967387/3d4f6a44-f334-11e6-8ea7-3b91172f2d81.jpg)


On desktop:

**Comment by sgerritse** [comment]
Look into the video responsiveness on mobile (http://www.mcaprotools.com/whatismca/)
![img_1134](https://cloud.githubusercontent.com/assets/10511034/23156806/6b43722c-f7e6-11e6-8e58-edc8ab0852f6.PNG)
![img_1135](https://cloud.githubusercontent.com/assets/10511034/23156808/6b46cb3e-f7e6-11e6-816c-cbb9de2482ab.PNG)
![img_1136](https://cloud.githubusercontent.com/assets/10511034/23156807/6b45cc52-f7e6-11e6-9967-5a4b455c9df6.PNG)

**Comment by sgerritse** [comment]
On this page: http://mcaprotools.com/mcaprotools-invite/

![img_1137](https://cloud.githubusercontent.com/assets/10511034/23156996/43656bd8-f7e7-11e6-8ade-cdcbac848fad.PNG)


The styling of the bullets should be more like http://www.mcaprotools.com/whatismca/

![img_1138](https://cloud.githubusercontent.com/assets/10511034/23157001/49232a88-f7e7-11e6-9dbf-c492a32c4b65.PNG)

**Comment by sgerritse** [comment]
On this page "http://www.mcaprotools.com/losingsleep/" remove the "arrow". 
![img_1180](https://cloud.githubusercontent.com/assets/10511034/23228189/aa4ac80c-f909-11e6-9226-ae13da122ab9.PNG)

**Comment by tarundhanwani** [comment]
Hi, all of the changes are in place for the responsive fixes including the comments above. Let me know if there are any other changes in terms of mobile or desktop views that need changing.

Thanks!
