### ISSUE TITLE
"Course Complete" function

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#25]
When a user completes a course, they don't really notice it. 

So...too remedy that, I would like to show user a "course completed" message.

![screen shot 2017-02-24 at 12 15 43 am](https://cloud.githubusercontent.com/assets/10511034/23291448/a44ec9c6-fa26-11e6-87f7-ecfd7122a532.png)

**Comment by tarundhanwani** [comment]
Hi, this is in place.

Thanks
