### ISSUE TITLE
"Lesson / Course" start buttons

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#26]
The buttons currently are super thin on mobile. 

![screen shot 2017-02-24 at 12 22 36 am](https://cloud.githubusercontent.com/assets/10511034/23291555/5c8b1fa8-fa27-11e6-94ca-191f08dec521.png)

They should look like this:

![img_1204](https://cloud.githubusercontent.com/assets/10511034/23291562/660b2104-fa27-11e6-8585-1aa73e6c0f81.PNG)

**Comment by tarundhanwani** [comment]
This is done.

Thanks
