### ISSUE TITLE
Mobile Menu Styling

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#27]
The lock icons look way to big for the menu. 

![screen shot 2017-02-24 at 12 24 39 am](https://cloud.githubusercontent.com/assets/10511034/23291607/a6ca32d4-fa27-11e6-9c76-bf173b3f9627.png)

They should look like this:

![screen shot 2017-02-24 at 12 27 23 am](https://cloud.githubusercontent.com/assets/10511034/23291676/090f290e-fa28-11e6-8c39-8456c0fa3bfb.png)

**Comment by tarundhanwani** [comment]
Hi, this is in place. See attached screenshot.

Thanks
![screen shot 2017-02-28 at 3 10 49 am](https://cloud.githubusercontent.com/assets/3523102/23375507/92ac8556-fd63-11e6-8944-174bfc1dea66.png)
