### ISSUE TITLE
MCA Username "Required"

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#28]
On this page: http://mcaprotools.com/lesson/connect-your-mca-username/

![img_1205](https://cloud.githubusercontent.com/assets/10511034/23291798/fc3506c6-fa28-11e6-974c-8cc0bf965152.PNG)

The Field should be required to be filled out, in order to move forward / or complete the lesson.

- Also make the "Click Here" in the "If you don't have an mca username" message below "red"

**Comment by tarundhanwani** [comment]
The changes for this task are done.

Thanks.
