### ISSUE TITLE
Course Completed Badge Changes

### ISSUE THREAD

**Issue by tarundhanwani** [MastermindMedia/MCAProTools#29]
1. Make the badge a text with icon plus dynamically generate name of course.
2. Make the badge appear in its own page and not in between/above an existing lesson.

Estimated hours for completion - 2 to 4 hours.

**Comment by tarundhanwani** [comment]
Hi, the modification for the badge course complete feature is in place. Converted from image to actual code with course name being dynamic.

Thanks

**Comment by sgerritse** [comment]
Good job, however it still shows the video at same time it is showing the course completed. 

The course completed function / badge is supposed to be by itself.

**Comment by tarundhanwani** [comment]
Video/lesson content should not show on the course completed badge page. Also, the course name should now be correct.

![screen shot 2017-03-23 at 2 20 15 pm](https://cloud.githubusercontent.com/assets/3523102/24234542/e25eb1b4-0fd3-11e7-960e-b3a211decd92.png)
