### ISSUE TITLE
Add Change Profile Picture Function

### ISSUE THREAD

**Issue by tarundhanwani** [MastermindMedia/MCAProTools#30]
Estimated hours for completion - 1 to 2 hours

**Comment by tarundhanwani** [comment]
This has been addressed, please see attached image. The profile picture upload feature is now available in the edit profile section of each users when they scroll to the bottom of their edit profile page. See attached.

Thanks
![Uploading Screen Shot 2017-03-06 at 9.07.09 PM.png…]()

**Comment by sgerritse** [comment]
The users do not have access to the backend of wordpress, EVER. 

This function needs to be on this page:
http://mcaprotools.com/my-account/edit-account/

Looking like this, or similar:
![screen shot 2017-03-14 at 4 37 21 pm](https://cloud.githubusercontent.com/assets/10511034/23921375/d3ef5454-08d4-11e7-8fd0-4c499f40148b.jpg)

**Comment by tarundhanwani** [comment]
An update to this, I've coded in the Change Profile Picture Function into the my account page of the user. http://mcaprotools.com/my-account/edit-account/ 
Next is styling it to make it look like the screenshot above.

Thanks

**Comment by tarundhanwani** [comment]
The styling is in place, I've also made the buttons consistent on the site's design.

Thanks

**Comment by sgerritse** [comment]
It does not show the profile picture here (Dashboard):
![Uploading Screen Shot 2017-04-01 at 6.36.54 PM.png…]()

**Comment by sgerritse** [comment]
It does not show in the dashboard when user signs in:

**Comment by sumeena** [comment]
Issue Resolved
