### ISSUE TITLE
Padding is odd on pages

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#36]
Look at the following pages:
http://www.mcaprotools.com/whatismca/

The Odd Looking Padding...
![screen shot 2017-03-14 at 4 10 37 pm](https://cloud.githubusercontent.com/assets/10511034/23920471/371f77ce-08d1-11e7-85b2-d79b3daade86.png)

Should look like this...
![screen shot 2017-03-14 at 4 15 21 pm](https://cloud.githubusercontent.com/assets/10511034/23920539/7d534798-08d1-11e7-96e1-4f7e54134c6e.png)

This section here looks odd (Ignore font sizing)..
![screen shot 2017-03-14 at 4 16 08 pm](https://cloud.githubusercontent.com/assets/10511034/23920584/ad4e1626-08d1-11e7-9f30-d4f1c9bbff56.png)

It should look more like this (Ignore font sizing)...
![screen shot 2017-03-14 at 4 16 51 pm](https://cloud.githubusercontent.com/assets/10511034/23920598/bbac6a10-08d1-11e7-8d6d-74bd0d511c14.png)

It seems that just about each section should have a padding-left & padding right of 200px. Not sure how you would do that in responsive, but that is how I was able to provide the screenshots.

**Comment by tarundhanwani** [comment]
Responsive padding/margin with percentage value has been added to the sides of the full width elements of the page.

Thanks
