### ISSUE TITLE
Extra "Proceed to Cart" link visible?

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#37]
Seems there is an additional link which shows, and is not needed because we have a huge button for this function already. (See Screenshot)

View the "Cart" page: http://mcaprotools.com/cart/
![screen shot 2017-03-14 at 4 21 38 pm](https://cloud.githubusercontent.com/assets/10511034/23920814/80baf042-08d2-11e7-9342-369103b1f1c0.png)

**Comment by tarundhanwani** [comment]
The extra Proceed to Checkout link/button has been removed.
