### ISSUE TITLE
The "Sign Up Now" button

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#39]
Go to http://mcaprotools.com/checkout/

![screen shot 2017-03-14 at 4 25 55 pm](https://cloud.githubusercontent.com/assets/10511034/23920917/f3f780ca-08d2-11e7-9d67-006564df1b22.png)

The "Sign Up Now" button should look like this:
![screen shot 2017-03-14 at 4 25 55 pm](https://cloud.githubusercontent.com/assets/10511034/23921031/732a3360-08d3-11e7-8d6b-1cd43a3da621.png)

**Comment by tarundhanwani** [comment]
Hi, this has been addressed.

Thanks
