### ISSUE TITLE
When user clicks "My Account" from dashboard

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#40]
When user clicks this "My Account" 
![screen shot 2017-03-14 at 4 41 17 pm](https://cloud.githubusercontent.com/assets/10511034/23921459/1fc9ebb4-08d5-11e7-93bc-9e48c30bab83.png)

They go to this page: http://mcaprotools.com/my-account/

![screen shot 2017-03-14 at 4 40 25 pm](https://cloud.githubusercontent.com/assets/10511034/23921487/31e201c4-08d5-11e7-953c-f90fa5411cf6.png)

...But, it shoulld really be going to this page:  http://mcaprotools.com/my-account/edit-account/

![screen shot 2017-03-14 at 4 37 21 pm](https://cloud.githubusercontent.com/assets/10511034/23921573/7eca7ebc-08d5-11e7-935e-73d19f16aa8d.jpg)

(http://mcaprotools.com/my-account/, should just redirect or change page template "edit-account" to become "account".

**Comment by tarundhanwani** [comment]
Hi, this has been done, I've added a redirect instead of changing the template since the page already exists.
