### ISSUE TITLE
After user completes "Marketing Section" course.

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#41]
After user completes the last "Marketing Section" course "http://mcaprotools.com/lesson/checking-marketing-stats/" it should display the "Completed Course Badge" & Green button which says "Go To Marketing Links..."

Currently it redirects back to "Training",
![screen shot 2017-03-14 at 5 13 49 pm](https://cloud.githubusercontent.com/assets/10511034/23922673/a7bc2c18-08d9-11e7-923a-45757b1a4dfc.png)

**Comment by tarundhanwani** [comment]
This has been addressed. Thanks.
