### ISSUE TITLE
My Account page - menu

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#44]
http://mcaprotools.com/my-account/ and all the pages listed here:

![screen shot 2017-04-01 at 4 21 12 pm](https://cloud.githubusercontent.com/assets/10511034/24582143/3d700fc4-16f7-11e7-85a6-279968097737.png)

The menu should be defined by the sidebar "My Account Menu": 

![screen shot 2017-04-01 at 4 20 32 pm](https://cloud.githubusercontent.com/assets/10511034/24582133/3344e0e2-16f7-11e7-9e88-626c7545cbd0.png)

**Comment by sumeena** [comment]
Issue Resolved
