### ISSUE TITLE
Modify Footer

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#45]
The footer should look like this: 
![footer](https://cloud.githubusercontent.com/assets/10511034/24582321/0d4ee686-16fb-11e7-96c8-d3f561b38fc2.jpg)

You can grab the logos from the bottom of this page: 
https://shop.economist.com/?_ga=1.65722411.407560655.1491079785

Menus should be pulled from "Footer" Menu (http://mcaprotools.com/wp-admin/nav-menus.php?menu=98)

**Comment by sumeena** [comment]
Issue Resolved.

**Comment by sgerritse** [comment]
![screen shot 2017-04-07 at 4 04 25 pm](https://cloud.githubusercontent.com/assets/10511034/24817819/f2545090-1bab-11e7-9250-2a8687d011c9.png)

This doesnt look like the above screenshot.

**Comment by tarundhanwani** [comment]
This is done, modified the cc image as well.

Thanks
