### ISSUE TITLE
Support Styling

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#47]
http://mcaprotools.com/support/

Should look like this:

![screen shot 2017-04-01 at 6 14 13 pm](https://cloud.githubusercontent.com/assets/10511034/24582871/c693b462-1707-11e7-905c-4e6ed8f88745.png)

**Comment by sumeena** [comment]
Do you want me to remove " Refund / Cancelation Policy" from support menu ?

**Comment by sumeena** [comment]
Issue Resolved.
