### ISSUE TITLE
"Push Start" page needs popup.

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#49]
http://mcaprotools.com/pushstart/ need JUST this popup, make sure it is embedded into template.

...You can see this function here: http://mcaprotools.com/whatismca (Minus the 1st popup)

![screen shot 2017-04-01 at 7 01 14 pm](https://cloud.githubusercontent.com/assets/10511034/24583092/9a1dc084-170d-11e7-9896-efe64fe71f07.png)

....to appear once the user clicks on the "buy button:
![screen shot 2017-04-01 at 7 00 26 pm](https://cloud.githubusercontent.com/assets/10511034/24583088/8afc71fe-170d-11e7-8707-cd0a5552d0eb.png)

**Comment by sumeena** [comment]
done
