### ISSUE TITLE
iFrame MCA Form

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#50]
On this page: http://mcaprotools.com/tvc/

When the user fills out the iframe form, they are forwarded to this page:

![screen shot 2017-04-01 at 10 52 16 pm](https://cloud.githubusercontent.com/assets/10511034/24584094/9cb2554a-172f-11e7-869e-a165dc3c1f76.png)

Which when they click the "Back to My Account" button, it brings them to the MCA Dashboard:

![screen shot 2017-04-01 at 10 53 45 pm](https://cloud.githubusercontent.com/assets/10511034/24584105/0178ec1e-1730-11e7-8834-c36dd58742d7.png)

...Is there a way to target the iframe to check for when the "Back to My Account" button appears?

![screen shot 2017-04-01 at 10 52 25 pm](https://cloud.githubusercontent.com/assets/10511034/24584097/a9107cae-172f-11e7-9cd7-ea2a224a159c.png)

This way, we can trigger this "Popup" upon completion of the iframe form, or when the "Back to My Account" button appears / button is clicked.

![screen shot 2017-04-01 at 7 01 14 pm](https://cloud.githubusercontent.com/assets/10511034/24584102/d58c17ca-172f-11e7-9469-6dd8d19acc24.png)

**Comment by sumeena** [comment]
Hello ,

As i checked we cannot check the cross domain iframe using the jquery.
for this we have to inherit the browser compatibity.

If we will  do this by inherit the browser . there is still one more problem,  the (back to my account) button has already a trigger action in that page

Thanks
