### ISSUE TITLE
Create Page & Add to Marketing Links

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#51]
This "page template" needs to be created:

![capture_mca](https://cloud.githubusercontent.com/assets/10511034/24585109/47dc59b4-1750-11e7-982e-b206fe0d478a.jpg)

This needs to follow the same rules as this capture page: http://www.mcaprotools.com/losingsleep/?ref=

...Add the page to the "Marketing Links": http://mcaprotools.com/marketing-hub/mca-business-links/ under "MCA Business / Capture Pages".

**Comment by sumeena** [comment]
Done
