### ISSUE TITLE
Viewing Permissions

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#52]
Whatever code is being used now is giving me nightmare & not admin friendly.

`function my_page_template_redirect()

{

    if (!is_user_logged_in()) {

        $login_page = home_url('/login');

        $guest_allowed = array(

            "whatismca",

            "benefits",

            "testimonials",

            "notsleepingvideo",

            "losingsleep",

            "2kperweek",

            "login",

            "invite",

            "checkout",

            "cart",

            "hangout",

            "pushstart",

            "support",

            "weekly",

            "tvc",

            "privacy-policy",

            "terms-of-use",

            "refund-cancelation-policy",

           

           

                   );

        if ($_SERVER['REQUEST_METHOD'] == 'GET' && !is_page($guest_allowed) && !url_segment(1) == 'store') && !url_segment(1) == 'product') {

            wp_redirect($login_page);

            exit;

        }

    }

    if (is_user_logged_in() && is_page('login')) {

        wp_redirect(home_url());

        exit;

    }

    global $current_user, $post;

    $classes = get_body_class();

    if (in_array('post-type-archive-course', $classes)) {

        wp_redirect('/training-hub/');

        exit;

    }

}

add_action('template_redirect', 'my_page_template_redirect');`

---

Currently when in use it breaks the website. So, we need to change this permission thing 100% so we can easily add new pages / see which pages guest can't view. Before we were using "restrict content pro", but it was too bulky.

![screen shot 2017-04-05 at 12 45 45 pm](https://cloud.githubusercontent.com/assets/10511034/24718649/d1461210-1a04-11e7-9fe4-ef498e420092.png)

I think just adding the option, "Member", to Page Visibility would make the page private, requiring active membership, (https://mcaprotools.com/product/membership/).

You don't need to specify "Guest" since "Public" is guest technically.

*Should work for Woocommerce Products too*

---

Here are the page permissions:

...By default, if a guest does not have permission to view page they would be redirected to: 
1. https://mcaprotools.com/login/

The homepage for the website when someone visits would be this page: 
1. https://mcaprotools.com/invite/

When a guest signs into a user account via login, the default page should be:
1. https://mcaprotools.com/dashboard/

Guest(s) CAN only publicly view following pages:
1. https://mcaprotools.com/whatismca/
2. https://mcaprotools.com/invite/
3. https://mcaprotools.com/cart/
4. https://mcaprotools.com/checkout/
5. https://mcaprotools.com/support/
6. https://mcaprotools.com/refund-cancelation-policy/
7. https://mcaprotools.com/privacy-policy/
8. https://mcaprotools.com/terms-of-use/
9. https://mcaprotools.com/benefits/
10. https://mcaprotools.com/blog/
11. https://mcaprotools.com/faq/
12. https://mcaprotools.com/2kperweek/
13. https://mcaprotools.com/hangout/
14. https://mcaprotools.com/testimonials/
15. https://mcaprotools.com/takeover/
16. https://mcaprotools.com/pushstart/
17. https://mcaprotools.com/no-access/
18. https://mcaprotools.com/store/
19. https://mcaprotools.com/tvc/
20. https://mcaprotools.com/weekly/
21. https://mcaprotools.com/mcaexplained/
22. https://mcaprotools.com/losingsleep/
23. https://mcaprotools.com/notsleepingvideo/

Members can see all the above pages and these pages:
1. https://mcaprotools.com/dashboard/
2. https://mcaprotools.com/courses/ & lessons
3. https://mcaprotools.com/cancel-account/
4. https://mcaprotools.com/logout/
5. https://mcaprotools.com/marketing-hub/
6. https://mcaprotools.com/marketing-hub/creatives/
7. https://mcaprotools.com/marketing-hub/marketing-faqs/
8. https://mcaprotools.com/marketing-hub/marketing-stats/
9. https://mcaprotools.com/marketing-hub/mca-business-links/
10. https://mcaprotools.com/marketing-hub/mpt-links/
11. https://mcaprotools.com/my-account/
12. https://mcaprotools.com/my-courses/
13. https://mcaprotools.com/offline-marketing/
14. https://mcaprotools.com/online-marketting/
15. https://mcaprotools.com/resources/
16. https://mcaprotools.com/support-tickets/
17. https://mcaprotools.com/training-hub/

**Comment by tarundhanwani** [comment]
The functionality is in place, in order to set the restriction permission to just members/signed up users, you can edit a page, post or product and click on the "Members Only" checkbox under the Page Restriction meta box, see screenshot attached.

Thanks
![screen shot 2017-04-07 at 10 18 53 am](https://cloud.githubusercontent.com/assets/3523102/24817458/22330f64-1c0f-11e7-8486-3eaabadaffd9.png)
