### ISSUE TITLE
Training Menu "Breakup"

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#56]
![screen shot 2017-04-20 at 12 59 58 pm](https://cloud.githubusercontent.com/assets/10511034/25242923/47ae19d2-25c9-11e7-8851-8f83982d7be1.png)

Currently the menu in "Training" shows all the courses in one menu. However, they are separated by "Course Category", and should display as so:

![screen shot 2017-04-20 at 12 49 25 pm](https://cloud.githubusercontent.com/assets/10511034/25242890/32276bf4-25c9-11e7-9deb-efa24d81eb6a.png)

Also pay attention to the "Title Change".

**Comment by tarundhanwani** [comment]
Hi, this is in place.

Thanks
