### ISSUE TITLE
Losing Sleep Pages

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#61]
1. http://www.mcaprotools.com/notsleepingvideo/
2. http://www.mcaprotools.com/losingsleep/

These two pages above "Losing Sleep" need to look exactly like this:

![screen shot 2017-04-24 at 2 43 36 pm](https://cloud.githubusercontent.com/assets/10511034/25353400/1bfd7b02-28fd-11e7-900a-d97fd50867cf.png)

![screen shot 2017-04-24 at 2 48 06 pm](https://cloud.githubusercontent.com/assets/10511034/25353399/1bf03942-28fd-11e7-8e18-61c0de89a239.png)

**Comment by webskycreative** [comment]
@sgerritse 
updated (desktop and mobile)
http://www.mcaprotools.com/notsleepingvideo/
http://www.mcaprotools.com/losingsleep/

thx

**Comment by sgerritse** [comment]
The "notsleepingvideo" page should have a video embed. 

![screen shot 2017-04-26 at 1 17 32 pm](https://cloud.githubusercontent.com/assets/10511034/25447568/ad2a40c4-2a83-11e7-8bad-8f89e2f90e85.png)

`<div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><iframe src="//fast.wistia.net/embed/iframe/0tx76zoest?seo=false&videoFoam=true" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="100%" height="100%"></iframe></div></div>`

**Comment by webskycreative** [comment]
@sgerritse 
fixed https://mcaprotools.com/notsleepingvideo/
video is fully responsive

thanks
