### ISSUE TITLE
2k Per Week Design Issues

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#62]
http://www.mcaprotools.com/2kperweek/

This page should look exactly like this:

![screen shot 2017-04-24 at 3 00 33 pm](https://cloud.githubusercontent.com/assets/10511034/25353990/297ef920-28ff-11e7-82fc-a584b30e6a97.png)

**Comment by webskycreative** [comment]
@sgerritse 

updated https://mcaprotools.com/2kperweek/

thx

**Comment by sgerritse** [comment]
@webskycreative , I noticed that the "Send The Video" button does not work.

Also, please make the font 16px, and #000;.

![screen shot 2017-04-26 at 1 09 07 pm](https://cloud.githubusercontent.com/assets/10511034/25447061/ab575e96-2a81-11e7-8598-01e4fd87b4fe.png)

**Comment by webskycreative** [comment]
@sgerritse 
fixed
https://mcaprotools.com/2kperweek/
"Send The Video" button is working fine
email field has required tag now
font size is 16px, color : #000

thanks
