### ISSUE TITLE
What Is MCA Page Styling

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#64]
http://www.mcaprotools.com/whatismca/ 

- The Video Wrapper is super large. It should be no lager than 840px.
- The "Crimson / Red" buttons need to be fixed. (Copy sizing / styling of the buttons from http://expertsecrets.com/freebook)

![screen shot 2017-04-24 at 7 28 59 pm](https://cloud.githubusercontent.com/assets/10511034/25362932/d920c046-2924-11e7-9f41-bea5c59b4a10.png)

- The "Benefits" are not showing the icons. ( You can download them here if you need too: https://drive.google.com/open?id=0B9QlVpKDdRNvUE12NTJESFg5ZDg )

![592dec0e-2840-11e7-9864-a52aadd9ddd6](https://cloud.githubusercontent.com/assets/10511034/25362911/bcf2f1fa-2924-11e7-93d1-fb57d774d9ad.jpg)

- The "Buy Price / Section" should be two columns, and the picture should be on the right. On the left, under the "Price" out a "Crimson / Red" button. (Make it look exactly like below.)

![screen shot 2017-04-24 at 7 35 02 pm](https://cloud.githubusercontent.com/assets/10511034/25363243/384746ba-2927-11e7-81ef-745a31139d72.jpg)

Also note that the "User Data" should be pulled from the "?Ref=USERNAME":

![user-data](https://cloud.githubusercontent.com/assets/10511034/25363266/4e26a6ba-2927-11e7-958c-bb8a97fe9971.jpg)

**Comment by tarundhanwani** [comment]
Hi, the changes are done, including the dynamic retrieval of the user data based on the Ref argument in the url. I also made it so that if there is no Ref then the user avatar/image would have a default image. I also added the retrieval of the user first and last names based at the very first sentence.

Please check and confirm, thanks.

**Comment by sgerritse** [comment]
The buttons should follow this:

![screen shot 2017-04-28 at 3 15 01 pm](https://cloud.githubusercontent.com/assets/10511034/25543692/8eab9744-2c25-11e7-99e6-530b4824d027.png)

element.style {
    text-align: center;
    margin: 0 auto;
    width: 80%;
}
