### ISSUE TITLE
Benefits Page Styling

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#65]
http://www.mcaprotools.com/benefits/

- Default width for this page should be 1080px, (Careful - other pages use "landing-box" class.
- All Text should be "align: left" not "center".)
- Fix the "Crimson / Red" buttons.
- Add the same icons from ("whatismca" page), to each Title. ( You can download them here if you need too: https://drive.google.com/open?id=0B9QlVpKDdRNvUE12NTJESFg5ZDg )

**Comment by webskycreative** [comment]
@sgerritse 

updated
http://www.mcaprotools.com/benefits/

Default width for this page should be 1080px, (Careful - other pages use "landing-box" class.
=> fixed

All Text should be "align: left" not "center".)
=> fixed

Fix the "Crimson / Red" buttons.
=> fixed

Add the same icons from ("whatismca" page), to each Title. ( You can download them here if you need too: https://drive.google.com/open?id=0B9QlVpKDdRNvUE12NTJESFg5ZDg )
=> not clear for me. "whatismca" page : https://mcaprotools.com/whatismca/ , right ? there is no icon on it's title ?

thanks

**Comment by webskycreative** [comment]
@sgerritse 
updated
https://mcaprotools.com/benefits/

do you have icon for "UNLIMITED Security Roadside Assistance" ?

thanks

**Comment by sgerritse** [comment]
@webskycreative just use: https://mcaprotools.com/wp-content/themes/mca-child/assets/img/benefits/stolen-vehicle-reward.svg

**Comment by sgerritse** [comment]
All those buttons should should have same popup as "whatismca" page.

**Comment by webskycreative** [comment]
@sgerritse 

updated
https://mcaprotools.com/benefits

now, all buttons have same pop up as "whatismca" page

thanks
