### ISSUE TITLE
MCA History Page

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#69]
https://mcaprotools.com/mcahistory/
- Fix "Crimson / Red" buttons.
- Can we make this "JPG" into a responsive timeline, actual text etc. (As close as possible, Users on Mobile can't currently see these images at all because it is a huge image.)

![mca_timeline](https://cloud.githubusercontent.com/assets/10511034/25363704/90ed00fe-292a-11e7-8e0f-62be3d0bcc88.png)

**Comment by webskycreative** [comment]
@sgerritse @tarundhanwani 
updated
https://mcaprotools.com/mcahistory/
(red button and timeline are looking good on desktop and mobile)

thanks
