### ISSUE TITLE
Hangout Page

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#72]
http://www.mcaprotools.com/hangout/
- Video Wrapper Needs to be fixed.
- Get Instant Coverage Button should link to this, using the "ref?=" code. 
`https://www.tvcmatrix.com/secure/cart/addItem.aspx?qty=1&amp;itID=9135&amp;PromoID=83&amp;uid=<?php if (isset($_GET['ref'])) echo $_GET['ref']; ?>`

- The "Still have questions?" button should link to the "whatismca" page, using the "ref?=" in the url.

**Comment by webskycreative** [comment]
@sgerritse 

updated http://www.mcaprotools.com/hangout/
- video is fixed

may i know url for "whatismca" page ?

thanks

**Comment by sgerritse** [comment]
http://mcaprotools.com/whatismca

**Comment by sgerritse** [comment]
The styling is not working properly because you didn't use the template. As we discussed please redo the styling but in the page-hangout.php
