### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#73]
https://mcaprotools.com/login/
- "Forgot password, should be on right side.
- Register button, should have same font style as login.

**Comment by webskycreative** [comment]
@sgerritse 

updated
https://mcaprotools.com/login/
-  "Forgot password" appear on right side now
-  "Register" button has same font style as login button

thanks

**Comment by sgerritse** [comment]
Check style error for when user logs out?
![screen shot 2017-04-28 at 2 52 01 am](https://cloud.githubusercontent.com/assets/10511034/25517499/b52cdcec-2bbd-11e7-9352-413a59ec8272.png)

**Comment by webskycreative** [comment]
@sgerritse 

fixed
https://www.screencast.com/t/wiqhPsRu2

thanks
