### ISSUE TITLE
My Account 

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#74]
https://mcaprotools.com/my-account/
- "Menu Styling" is not same as the rest of the website.
![screen shot 2017-04-24 at 8 27 44 pm](https://cloud.githubusercontent.com/assets/10511034/25363939/bf20718e-292c-11e7-9b01-8d884f2ccaf0.png)

**Comment by sgerritse** [comment]
Please fix the "Upload Photo", I am going to leave it up to you to style it @tarundhanwani 

Use all the elements shown.

![screen shot 2017-04-28 at 10 59 20 pm](https://cloud.githubusercontent.com/assets/10511034/25552387/64488b10-2c66-11e7-8f7f-09ff88f9029e.png)

**Comment by sgerritse** [comment]
It should look like this:

![screen shot 2017-04-29 at 11 20 52 pm](https://cloud.githubusercontent.com/assets/10511034/25561120/8a450998-2d32-11e7-9263-43f1bd60e2a4.png)

**Comment by sgerritse** [comment]
I noticed when i sign into the account "Felontofortune" he doesnt see any of the "upload / choose image / etc." section at all?

![screen shot 2017-04-30 at 1 20 07 am](https://cloud.githubusercontent.com/assets/10511034/25561892/29c278d8-2d43-11e7-81f2-be60403a208e.png)

**Comment by tarundhanwani** [comment]
My account menu styling has been fixed. Working on the design of the upload photo section to match the above design. Also, will investigate what the issue is regarding the upload photo not showing up for the Felontofortune account.

Thanks

**Comment by sgerritse** [comment]
Resolved & Permission / Role issue is resolved too.
