### ISSUE TITLE
Support Page 

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#75]
https://mcaprotools.com/support/
- "Menu Styling" is not same as the rest of the website.
- Says "Permission" Error:

![screen shot 2017-04-24 at 8 31 21 pm](https://cloud.githubusercontent.com/assets/10511034/25363981/0844c4a0-292d-11e7-9d20-91db39558404.png)

**Comment by tarundhanwani** [comment]
This was a tricky one, but I managed to solve it. Customers can now submit support tickets.

Also, I fixed the menu styling to be consistent.

Thanks
