### ISSUE TITLE
Support Tickets

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#76]
https://mcaprotools.com/support-tickets/
- Says "Permission" Error: 
![screen shot 2017-04-24 at 8 31 21 pm](https://cloud.githubusercontent.com/assets/10511034/25363981/0844c4a0-292d-11e7-9d20-91db39558404.png)

**Comment by sgerritse** [comment]
Also, please style the page form so that it follows this design:

![screen shot 2017-04-27 at 11 16 03 pm](https://cloud.githubusercontent.com/assets/10511034/25512960/8cf281dc-2b9f-11e7-9b1f-5326af51b6f2.png)

**Comment by tarundhanwani** [comment]
Hi @sgerritse , the permission has been fixed. Also, the form design has been altered to match the above design - https://mcaprotools.com/support/

Do you have a design in mind for this page - https://mcaprotools.com/support-tickets/ ?

Thanks

**Comment by sgerritse** [comment]
Here is the design for the "reply", as you requested.

![support-reply](https://cloud.githubusercontent.com/assets/10511034/25566310/6d1886e8-2da4-11e7-90bb-7097de143dd8.jpg)

You may not be able to do the top portion, I am not entirely sure (I pulled this from the Admin - I think it is important that the customer / user know these details too):
![screen shot 2017-04-30 at 12 56 09 pm](https://cloud.githubusercontent.com/assets/10511034/25566314/70739544-2da4-11e7-84d6-e09504585a56.png)
