### ISSUE TITLE
Resources Page

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#78]
https://mcaprotools.com/resources/
- Fix the styling in this section to look exactly like this:
![screen shot 2017-04-24 at 8 39 35 pm](https://cloud.githubusercontent.com/assets/10511034/25364143/346d5cbc-292e-11e7-9d86-5cdfea63b45a.png)

- When you click on a product, in the description it is showing the product image again. We don't need that to show again.

- Remove "Breadcrumbs" -- DIRECTLY --- above the product image.

- Make the page look exactly like this:
![screen shot 2017-04-24 at 8 46 03 pm](https://cloud.githubusercontent.com/assets/10511034/25364291/52b5a584-292f-11e7-95df-b52cb55e91b1.png)

**Comment by webskycreative** [comment]
@sgerritse 

updated
https://mcaprotools.com/resources/
https://mcaprotools.com/product/mca-8-5-x-11-flyers/ (single product)

thanks
