### ISSUE TITLE
Store Page

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#79]
https://mcaprotools.com/store/
- Should follow the same styling as "resources" page.

**Comment by sgerritse** [comment]
#content {
    width: 100%;
}

.woocommerce ul.products li {
    padding: 15px;
    height: 100%;
    min-height: 400px;
    width: 250px;
}

h2.woocommerce-loop-product__title {
    font-size: 24px !important;
    padding: 10px;
    padding-left: 0px;
    padding-right: 0px;
}

-----------

Which made it look like this. 4 columns, larger font etc.

![screen shot 2017-04-27 at 10 55 18 pm](https://cloud.githubusercontent.com/assets/10511034/25512555/ae1cdef0-2b9c-11e7-95e0-324185c221a2.png)

**Comment by webskycreative** [comment]
@sgerritse 

updated https://mcaprotools.com/store/

thanks

**Comment by sgerritse** [comment]
Still has issues.

![screen shot 2017-04-28 at 10 54 58 pm](https://cloud.githubusercontent.com/assets/10511034/25552381/1acf1d78-2c66-11e7-87a7-f18e6e0da66e.png)

**Comment by webskycreative** [comment]
@sgerritse 

fixed
https://mcaprotools.com/store/

thanks
