### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#85]
https://mcaprotools.com/privacy-policy/
- "Menu Styling" is not same as the rest of the website.

![screen shot 2017-04-24 at 9 02 57 pm](https://cloud.githubusercontent.com/assets/10511034/25364590/7a415236-2931-11e7-811d-309ba512ec4d.png)

**Comment by tarundhanwani** [comment]
This has been fixed.

Thanks
