### ISSUE TITLE
Add Variations

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#91]
The following pages need to have the following functions. (You need to create the page template for these using the "tvc template").

- "User Must Click Button For Form Too Appear"
https://mcaprotools.com/tvcbtn/

- "The Button & The Form Are Delay (display: none) for "1:00"
https://mcaprotools.com/tvcfd/

(See example here: https://www.dailyincomemethod.com/vsltimer/?referid=Javiermedina9)

**Comment by webskycreative** [comment]
@sgerritse 

fixed
https://mcaprotools.com/tvcbtn/
User must click button for form to appear

fixed https://mcaprotools.com/tvcfd/
The Form Are Delay (display: none) for "1:00"

videos on those pages are responsive

Thanks
