### ISSUE TITLE
Add Two Generic Capture Pages

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#92]
To Be Added

**Comment by sgerritse** [comment]
Capture Page One "White with Video Background":
![white-cap](https://cloud.githubusercontent.com/assets/10511034/25515602/b585d3e2-2bb3-11e7-99e3-1ecfc48087a4.jpg)

Video Background Should Be This:
https://drive.google.com/open?id=0B9QlVpKDdRNvVklXNjNfR21tTjA

Which came from:
http://www.coverr.co/ 

![screen shot 2017-04-28 at 1 46 24 am](https://cloud.githubusercontent.com/assets/10511034/25515722/84616f50-2bb4-11e7-8dbc-951e0af6d5ae.png)


--------

**Comment by sgerritse** [comment]
Capture Pages Two Should Be:
![transparent-cap](https://cloud.githubusercontent.com/assets/10511034/25516819/87a836d4-2bba-11e7-883a-c4eada03dd3f.jpg)

Using this BG Image, "Position Right"
![panorama-2117310_1920](https://cloud.githubusercontent.com/assets/10511034/25516821/8ca2714a-2bba-11e7-9484-efb106b9144b.jpg)

**Comment by webskycreative** [comment]
@sgerritse 

updated
https://mcaprotools.com/secret/

thanks

**Comment by webskycreative** [comment]
@sgerritse 

updated 
https://mcaprotools.com/6figbiz/

thanks
