### ISSUE TITLE
Fix Buy Popup

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#94]
![screen shot 2017-04-28 at 11 34 57 pm](https://cloud.githubusercontent.com/assets/10511034/25552571/710f8b32-2c6b-11e7-8069-74b0a03bac62.png)

- Fix the "Close" (DONE ALREADY)
- Fix the "Crimson" buy now" button.

(Keep in mind this is on many other pages too - styling is messed up, hopefully this popup css is sitewide.)

**Comment by webskycreative** [comment]
@sgerritse 

fixed https://www.screencast.com/t/gKCQXbAXk

thanks
