### ISSUE TITLE
Course Styling / Pricing

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#96]
![screen shot 2017-04-29 at 1 17 26 pm](https://cloud.githubusercontent.com/assets/10511034/25557388/3a924c2a-2cde-11e7-975e-d09a006e78f4.png)

I'm not sure how we can fix this, do this - however the "system training" is is all "one package / one price" even though they are 3 different courses...They should be $25.00 for all three courses, not $25 per course.

- Remove the pricing from the menu area.
- When user doesn't own "Products" make sure the menu shows the locked icon.

**Comment by sgerritse** [comment]
When A User Only Purchases any of the "Expert Training" trainings / or https://mcaprotools.com/course/6-figures-formula/ WITHOUT the MCA Pro Tools membership. 

...The "Expert Trainings" should be at the top menu, since they dont have the other trainings.

**Comment by sgerritse** [comment]
Also Make sure to style the course buy buttons and course video:
https://mcaprotools.com/course/6-figures-formula/

![screen shot 2017-04-30 at 1 16 22 am](https://cloud.githubusercontent.com/assets/10511034/25561869/a67ba198-2d42-11e7-890a-98b0dc7dad89.png)


It should look like this: 

![screen shot 2017-04-30 at 1 15 24 am](https://cloud.githubusercontent.com/assets/10511034/25561867/957ba942-2d42-11e7-911f-1e5739658dd2.png)

**Comment by sgerritse** [comment]
Noticed this is out of style too:
![screen shot 2017-04-30 at 1 06 38 pm](https://cloud.githubusercontent.com/assets/10511034/25566405/eb43cf22-2da5-11e7-8a8e-c77dd42ef79c.png)

**Comment by tarundhanwani** [comment]
Hi, the changes are in place.

Thanks
