### ISSUE TITLE
Two Button Video Page

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#97]
https://mcaprotools.com/bizvideo/

Buttons at the bottom should be two columns, and should look like this:

![screen shot 2017-04-30 at 3 13 21 am](https://cloud.githubusercontent.com/assets/10511034/25562396/16e7401c-2d53-11e7-80ca-de2bf892e2ab.png)

**Comment by webskycreative** [comment]
@sgerritse 

fixed https://mcaprotools.com/bizvideo/ (desktop and mobile)

Thanks
