### ISSUE TITLE
Dashboard Course Styling

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/MCAProTools#98]
This is how it currently looks:

![screen shot 2017-04-30 at 3 24 36 am](https://cloud.githubusercontent.com/assets/10511034/25562467/922bb8d8-2d54-11e7-84ba-a9f137ce4534.png)

![screen shot 2017-04-30 at 3 24 32 am](https://cloud.githubusercontent.com/assets/10511034/25562468/922d1d5e-2d54-11e7-8d47-4b54c70f4261.png)

On the Dashboard the Course Styling Under The Video Should Look like This:

![screen shot 2017-04-30 at 3 23 25 am](https://cloud.githubusercontent.com/assets/10511034/25562460/7a83eb24-2d54-11e7-89e4-ccb52c61ab8f.png)

![screen shot 2017-04-30 at 3 23 31 am](https://cloud.githubusercontent.com/assets/10511034/25562461/7a84e06a-2d54-11e7-84c5-4a392e3a3f35.png)

**Comment by webskycreative** [comment]
@sgerritse 

dashboard is updated
https://www.screencast.com/t/dbMw9i3m

thanks

**Comment by sgerritse** [comment]
This actually doesn't exist on the dashboard anymore, but it exist here:

https://mcaprotools.com/training-hub/ (under completed courses "tab")

The "reset function" works properly, however the issue is that it locks the first lesson of the "reset'ed" course. So the user, can't actually start the first lesson in the course. (Or was is there suppose to be a green "start course" button?)
